# Generated by Django 4.2.25 on 2025-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.TextField()),
                ('name', models.TextField(max_length=40)),
                ('stud_calss', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
